### ISSUE TITLE
option to open every link in default browser

### ISSUE THREAD

**Issue by mjabdulm** [kumar303/default-opener#3]
Hi,

Could you please add an option to open every link in default browser?

Thanks
Abdul

**Comment by kumar303** [comment]
Hi, thanks for your interest. I'm afraid I don't think that's possible from an extension.

**Comment by mjabdulm** [comment]
Thanks a lot. I can live with that.

 I had the same problem as you faced in my Mac...Safari(for all) vs Chrome(for Gmail).

This extension did solve my major problem.
